services:
  db:
    image: postgres:15-alpine
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${SUPERUSER_DB_USER}
      - POSTGRES_PASSWORD=${SUPERUSER_DB_PASSWORD}
      - POSTGRES_DB=${SUPERUSER_DB_NAME}
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${SUPERUSER_DB_USER} -d ${SUPERUSER_DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    container_name: medi_manager_db
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    container_name: medi_manager_redis
    restart: unless-stopped

  web:
    build: .
    command: python3 manage.py runsslserver --certificate ./localhost+2.pem --key ./localhost+2-key.pem 0.0.0.0:8000
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    env_file:
      - .env
    environment:
      - TZ=Asia/Tashkent
      - DATABASE=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SUPERUSER_PASSWORD=admin123
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    container_name: medi_manager_web
    restart: unless-stopped

  celery_worker:
    build: .
    command: celery -A core worker --loglevel=info
    volumes:
      - media_volume:/app/media
    env_file:
      - .env
    environment:
      - TZ=Asia/Tashkent
      - DATABASE=postgres
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    container_name: medi_manager_celery_worker
    restart: unless-stopped

  celery_beat:
    build: .
    command: celery -A core beat --loglevel=info
    env_file:
      - .env
    environment:
      - TZ=Asia/Tashkent
      - DATABASE=postgres
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    container_name: medi_manager_celery_beat
    restart: unless-stopped

volumes:
  postgres_data:
  static_volume:
  media_volume:
