# Generated by Django 4.2.20 on 2025-03-22 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_user_organization"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="created_by",
        ),
    ]
