# Generated by Django 4.2.20 on 2025-03-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_organization_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="device_limit",
            field=models.PositiveIntegerField(default=5),
        ),
    ]
