# Generated by Django 4.2.20 on 2025-03-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
