# Generated by Django 4.2.20 on 2025-03-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_alter_device_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="token",
            field=models.CharField(max_length=512, null=True),
        ),
    ]
