# Generated by Django 4.2.20 on 2025-03-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_device_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="token",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
