# Generated by Django 4.2.20 on 2025-10-03 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_users_userprofile_user_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='device_limit',
        ),
    ]
