# Generated by Django 4.2.20 on 2025-10-03 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_userprofile_device_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='current_device_count',
        ),
    ]
