server {
    listen 443 ssl;
    server_name _;

    client_max_body_size 1000M;
   
 # Sertifikatlar yo'li
    ssl_certificate /etc/nginx/certs/localhost+2.pem;
    ssl_certificate_key /etc/nginx/certs/localhost+2-key.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    # Frontend build folder
    root /frontend/dist;
    index index.html;

    # Frontend assets
    location /assets/ {
        try_files $uri =404;
        expires 30d;
        access_log off;
    }

    # Frontend SPA routes
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Django API
    location /api/ {
        proxy_pass http://web:8000;  # HTTP, Django container
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }

    # Django admin
    location /admin/ {
        proxy_pass http://web:8000;  # HTTP
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }

    # Swagger
    location /swagger/ {
        proxy_pass http://web:8000;  # HTTP
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }

    # Media files
    location /media/ {
        alias /app/media/;
    }

    # Static files
    location /static/ {
        alias /static/;
    }
}

# HTTPni HTTPSga yo'naltirish
server {
    listen 80;
    server_name _;

    return 301 https://$host$request_uri;
}
