# Generated by Django 4.2.20 on 2025-12-01 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'verbose_name': 'File', 'verbose_name_plural': 'Files'},
        ),
    ]
