# Generated by Django 4.2.20 on 2025-12-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0002_alter_attachment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='gif',
            field=models.FileField(blank=True, null=True, upload_to='attachments/gifs/'),
        ),
    ]
