# Generated by Django 5.2.4 on 2026-05-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attachment", "0003_attachment_gif"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceTimeReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=255, unique=True)),
                ("last_reported_time", models.DateTimeField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
