# Generated by Django 4.2.23 on 2025-07-19 06:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organization_device_id",
                    models.PositiveIntegerField(
                        help_text="Device ID within the organization (starts from 1)"
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("serial_number", models.CharField(max_length=255, unique=True)),
                ("exit_password", models.CharField(default="1111", max_length=255)),
                ("token", models.CharField(blank=True, max_length=512, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Device",
                "verbose_name_plural": "Devices",
                "db_table": "devices",
                "ordering": ["organization", "organization_device_id"],
            },
        ),
        migrations.CreateModel(
            name="DeviceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Device Type",
                "verbose_name_plural": "Device Types",
                "db_table": "device_types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Media",
            fields=[
                ("media_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[("video", "Video"), ("image", "Image")], max_length=10
                    ),
                ),
                ("file", models.FileField(upload_to="")),
                ("duration", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Media",
                "verbose_name_plural": "Media",
                "db_table": "media",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "device_limit",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Maximum number of devices allowed for this organization",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "current_device_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Current number of devices in use"
                    ),
                ),
                (
                    "next_device_id",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Next available device ID for this organization",
                    ),
                ),
                (
                    "expiration_date",
                    models.DateField(
                        blank=True,
                        help_text="Organization subscription expiration date",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this organization is active"
                    ),
                ),
                ("db_name", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
                "db_table": "organizations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Playlist",
            fields=[
                ("playlist_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "devices",
                    models.ManyToManyField(
                        related_name="playlists", to="organizations.device"
                    ),
                ),
                (
                    "media",
                    models.ManyToManyField(
                        related_name="playlists", to="organizations.media"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playlists",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Playlist",
                "verbose_name_plural": "Playlists",
                "db_table": "playlists",
                "ordering": ["-created_at"],
            },
        ),
    ]
