# Generated by Django 5.2.4 on 2025-07-25 10:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="db_name",
        ),
    ]
