# Generated by Django 4.2.20 on 2025-10-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_check_and_rewrite_old_objects_local_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playlist',
            name='playlist_type',
            field=models.CharField(choices=[('event', 'Event'), ('permanent', 'Permanent')], default='permanent', max_length=20),
        ),
        migrations.AddField(
            model_name='playlist',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
