# Generated by Django 4.2.20 on 2025-11-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_remove_file_file_remove_file_name_file_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
