# Generated by Django 4.2.20 on 2025-11-20 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='slug',
        ),
    ]
