# Generated by Django 4.2.20 on 2025-12-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0011_device_created_by_device_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='config',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='is_widget',
            field=models.BooleanField(default=False),
        ),
    ]
