# Generated by Django 4.2.20 on 2025-12-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0012_file_config_file_is_widget'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='expiration_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
