# Generated by Django 5.2.4 on 2026-04-01 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0014_alter_device_device_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetype',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_types', to='organizations.organization'),
        ),
    ]
