# Generated by Django 5.2.4 on 2026-05-04 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attachment", "0003_attachment_gif"),
        ("organizations", "0016_devicegroup"),
    ]

    operations = [
        migrations.CreateModel(
            name="IoTDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=100, unique=True)),
                ("public_key", models.TextField()),
                ("name", models.CharField(blank=True, max_length=255)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name="file",
            name="attachment_widget",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="files_widget",
                to="attachment.attachment",
            ),
        ),
    ]
